/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tecmis;

import com.mysql.jdbc.Connection;
import java.sql.CallableStatement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static tecmis.AdminDashboard.editNoticeId;

/**
 *
 * @author sanda
 */
public final class EditNotice extends javax.swing.JFrame {

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    Connection con = null;
    ResultSet rs=null;
    PreparedStatement ps = null;
    CallableStatement cs=null;
    
    String editId = null;
    
    /** Creates new form EditNotice */
    public EditNotice() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("/image/tecmis.png")).getImage());
        
        editId = AdminDashboard.editNoticeId;
        getEditData();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateNotice = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        noticeNo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        noticeDate = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        noticeTitle = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        notice = new javax.swing.JTextArea();
        btnUpdateNotice = new javax.swing.JButton();
        btnCancelNotice = new javax.swing.JButton();
        noticeMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Notice");

        updateNotice.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(13, 20, 40));
        jLabel18.setText("Notice No :");

        noticeNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noticeNo.setText("Nxxxx");
        noticeNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        noticeNo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noticeNoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                noticeNoMouseExited(evt);
            }
        });
        noticeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeNoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(13, 20, 40));
        jLabel19.setText("Date :");

        noticeDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        noticeDate.setDateFormatString("yyyy-MM-d");
        noticeDate.setEnabled(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(13, 20, 40));
        jLabel20.setText("Notice Title :");

        noticeTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noticeTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        noticeTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticeTitleActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(13, 20, 40));
        jLabel21.setText("Notice :");

        notice.setColumns(32);
        notice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        notice.setRows(4);
        notice.setTabSize(2);
        notice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        jScrollPane2.setViewportView(notice);

        btnUpdateNotice.setBackground(new java.awt.Color(0, 137, 95));
        btnUpdateNotice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateNotice.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateNotice.setText("Update");
        btnUpdateNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNoticeActionPerformed(evt);
            }
        });

        btnCancelNotice.setBackground(new java.awt.Color(0, 137, 95));
        btnCancelNotice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelNotice.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelNotice.setText("Cancel");
        btnCancelNotice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelNoticeActionPerformed(evt);
            }
        });

        noticeMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noticeMessage.setForeground(new java.awt.Color(0, 137, 95));
        noticeMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout updateNoticeLayout = new javax.swing.GroupLayout(updateNotice);
        updateNotice.setLayout(updateNoticeLayout);
        updateNoticeLayout.setHorizontalGroup(
            updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateNoticeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(updateNoticeLayout.createSequentialGroup()
                        .addComponent(btnUpdateNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnCancelNotice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateNoticeLayout.createSequentialGroup()
                        .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(109, 109, 109)
                        .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(noticeNo, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(noticeDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(noticeTitle))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(noticeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        updateNoticeLayout.setVerticalGroup(
            updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateNoticeLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(noticeNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(noticeDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(noticeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(updateNoticeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateNotice)
                    .addComponent(btnCancelNotice))
                .addGap(33, 33, 33)
                .addComponent(noticeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(updateNotice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(updateNotice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noticeNoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeNoMouseClicked
        noticeNo.setText("N");
    }//GEN-LAST:event_noticeNoMouseClicked

    private void noticeNoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeNoMouseExited
        if(noticeNo.getText().equals("N")){
            noticeNo.setText("Nxxxx");
        }
    }//GEN-LAST:event_noticeNoMouseExited

    private void noticeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeNoActionPerformed

    private void noticeTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticeTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noticeTitleActionPerformed

    private void btnUpdateNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNoticeActionPerformed

        noticeMessage.setText(null);

        boolean flag;

        Notice c = new Notice();

        String id = noticeNo.getText().trim();
        String title = noticeTitle.getText().trim();
        Date bd;
        String d = null;
        String content = notice.getText().trim();

        try {
            bd = noticeDate.getDate();
            d = dateFormat.format(bd);
        } catch (Exception e) {
            noticeMessage.setText("Please fill all the fields correctly");
        }
        finally{
            if(id.isEmpty() || title.isEmpty())
            noticeMessage.setText("Please fill all the fields correctly");
            else{
                c.setId(id);
                c.setDate(d);
                c.setTitle(title);
                c.setContent(content);

                flag = c.editNotice();

                if(flag){
                this.setVisible(false);
                editNoticeId = null;
            }
            }
        }
    }//GEN-LAST:event_btnUpdateNoticeActionPerformed

    private void btnCancelNoticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelNoticeActionPerformed
        editNoticeId = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelNoticeActionPerformed

    public void getEditData() {
        con = DBConnect.connect();
        
        try {
            cs = con.prepareCall("{call `SearchNoticeDetails`('"+editId+"')}");
            rs = cs.executeQuery();
            
            if(rs.next()){
                noticeNo.setText(rs.getString("Notice No"));
                noticeDate.setDate(rs.getDate("Date"));
                noticeTitle.setText(rs.getString("Notice Title"));
                notice.setText(rs.getString("Notice"));
           }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditNotice().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelNotice;
    private javax.swing.JButton btnUpdateNotice;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea notice;
    private com.toedter.calendar.JDateChooser noticeDate;
    private javax.swing.JLabel noticeMessage;
    private javax.swing.JTextField noticeNo;
    private javax.swing.JTextField noticeTitle;
    private javax.swing.JPanel updateNotice;
    // End of variables declaration//GEN-END:variables

}
