/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecmis;

import com.mysql.jdbc.Connection;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;

import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static tecmis.AdminDashboard.editUserId;
/**
 *
 * @author sanda
 */
public final class EditProfile extends javax.swing.JFrame {

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    
    String editId;
    
    Connection con = null;
    ResultSet rs=null;
    CallableStatement cs=null;
    /**
     * Creates new form EditProfile
     */
    public EditProfile() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("/image/tecmis.png")).getImage());
        
        editId = AdminDashboard.editUserId;
        getEditData();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addUser = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userFName = new javax.swing.JTextField();
        userLName = new javax.swing.JTextField();
        userGender = new javax.swing.JComboBox<>();
        userNicNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userAddress = new javax.swing.JTextArea();
        userContactNo = new javax.swing.JTextField();
        userEmail = new javax.swing.JTextField();
        userId = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        userProfilePic = new javax.swing.JLabel();
        userPassword = new javax.swing.JPasswordField();
        userDepartment = new javax.swing.JComboBox<>();
        btnUpdateUser = new javax.swing.JButton();
        btnCancelEditUser = new javax.swing.JButton();
        userShowPassword = new javax.swing.JCheckBox();
        userDob = new com.toedter.calendar.JDateChooser();
        btnUpdateImage = new javax.swing.JButton();
        addUserMessage = new javax.swing.JLabel();
        userType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Profile");

        addUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(13, 20, 40));
        jLabel10.setText("Department :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 20, 40));
        jLabel1.setText("Id :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 20, 40));
        jLabel2.setText("First Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 20, 40));
        jLabel3.setText("Last Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 20, 40));
        jLabel4.setText("Contact Number :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(13, 20, 40));
        jLabel5.setText("Email :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 20, 40));
        jLabel6.setText("Gender :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(13, 20, 40));
        jLabel7.setText("Address :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(13, 20, 40));
        jLabel8.setText("NIC No :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(13, 20, 40));
        jLabel9.setText("DoB :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(13, 20, 40));
        jLabel11.setText("Password :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(13, 20, 40));
        jLabel12.setText("Type :");

        userFName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userFName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));

        userLName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userLName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));

        userGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        userGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        userGender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        userNicNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userNicNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));

        userAddress.setColumns(9);
        userAddress.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userAddress.setRows(4);
        userAddress.setTabSize(2);
        userAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        jScrollPane1.setViewportView(userAddress);

        userContactNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userContactNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));

        userEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));

        userId.setEditable(false);
        userId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userId.setText("adm");
        userId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        userId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdActionPerformed(evt);
            }
        });

        userProfilePic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userProfilePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/picture.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProfilePic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userProfilePic, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        userPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userPassword.setText("123");
        userPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));

        userDepartment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ICT", "ENT", "BST" }));
        userDepartment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        userDepartment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userDepartment.setEnabled(false);
        userDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDepartmentActionPerformed(evt);
            }
        });

        btnUpdateUser.setBackground(new java.awt.Color(0, 137, 95));
        btnUpdateUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateUser.setText("Update");
        btnUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateUserActionPerformed(evt);
            }
        });

        btnCancelEditUser.setBackground(new java.awt.Color(0, 137, 95));
        btnCancelEditUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelEditUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelEditUser.setText("Cancel");
        btnCancelEditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelEditUserActionPerformed(evt);
            }
        });

        userShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        userShowPassword.setText("Show Password");
        userShowPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userShowPasswordActionPerformed(evt);
            }
        });

        userDob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));
        userDob.setDateFormatString("yyyy-MM-d");

        btnUpdateImage.setBackground(new java.awt.Color(0, 137, 95));
        btnUpdateImage.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateImage.setText("Add Image");

        addUserMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addUserMessage.setForeground(new java.awt.Color(0, 137, 95));
        addUserMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        userType.setEditable(false);
        userType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        userType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 137, 95)));

        javax.swing.GroupLayout addUserLayout = new javax.swing.GroupLayout(addUser);
        addUser.setLayout(addUserLayout);
        addUserLayout.setHorizontalGroup(
            addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserLayout.createSequentialGroup()
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(140, 140, 140)))
                        .addComponent(userFName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addUserMessage)
                        .addGroup(addUserLayout.createSequentialGroup()
                            .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addUserLayout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(145, 145, 145))
                                    .addGroup(addUserLayout.createSequentialGroup()
                                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(59, 59, 59)))
                                .addGroup(addUserLayout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(91, 91, 91)))
                            .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(addUserLayout.createSequentialGroup()
                                    .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(userContactNo)
                                        .addComponent(userLName)
                                        .addComponent(userGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userNicNo)
                                        .addComponent(userDob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(addUserLayout.createSequentialGroup()
                                            .addGap(54, 54, 54)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(addUserLayout.createSequentialGroup()
                                            .addGap(30, 30, 30)
                                            .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnUpdateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(addUserLayout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(userShowPassword))))))
                                .addGroup(addUserLayout.createSequentialGroup()
                                    .addComponent(userDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelEditUser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addUserLayout.createSequentialGroup()
                                        .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel1)
                                        .addGap(69, 69, 69)
                                        .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnUpdateImage, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        addUserLayout.setVerticalGroup(
            addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addUserLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addUserLayout.createSequentialGroup()
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(userType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(userFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(userLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(userDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(userGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(userNicNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addUserLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateImage)
                        .addGap(52, 52, 52)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(userId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(addUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(userDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateUser)
                    .addComponent(btnCancelEditUser))
                .addGap(18, 18, 18)
                .addComponent(addUserMessage)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(addUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdActionPerformed

    }//GEN-LAST:event_userIdActionPerformed

    private void userDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDepartmentActionPerformed

    private void btnUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateUserActionPerformed
        boolean flag;
        
        User usr = new User();
        
        Object gender = userGender.getSelectedItem();
        Object dept = userDepartment.getSelectedItem();

        String uid = userId.getText().trim();
        String urole = userType.getText().trim();
        String ufName = userFName.getText().trim();
        String ulName = userLName.getText().trim();
        Date bd = null;
        String udob = null;
        String ugender;
        String unic = userNicNo.getText().trim();
        String uaddress = userAddress.getText().trim();
        String ucontact = userContactNo.getText().trim();
        String uemail = userEmail.getText().trim();
        String udepartment = dept.toString().trim();
        String upassword = userPassword.getText().trim();
        String uprofilePic = null;

        if(gender.toString().trim().equals("Male")){
            ugender = "M";
        }
        else{
            ugender = "F";
        }

        try {
            bd = userDob.getDate();
            udob = dateFormat.format(bd);
        } catch (Exception e) {
            addUserMessage.setText("Please fill all the fields correctly");
        }
        finally{
            if(ufName.isEmpty() || ulName.isEmpty() || bd == null || unic.isEmpty() || ucontact.isEmpty() || uemail.isEmpty() || upassword.isEmpty() || uaddress.isEmpty())
            addUserMessage.setText("Please fill all the fields correctly");
            else if(uid.equals("ad") || uid.equals("lc") || uid.equals("tc") || uid.equals("tg")){
                addUserMessage.setText("Enter valid user id");
            }
            else{
                usr.setId(editId);
                usr.setfName(ufName);
                usr.setlName(ulName);
                usr.setDob(udob);
                usr.setGender(ugender);
                usr.setNic(unic);
                usr.setAddress(uaddress);
                usr.setContact(ucontact);
                usr.setEmail(uemail);
                usr.setId(uid);
                usr.setPassword(upassword);
                
                flag = usr.editUser();
                
                if(flag){
                    editUserId = null;
                    this.setVisible(false);
                }
            }
        }

    }//GEN-LAST:event_btnUpdateUserActionPerformed

    private void btnCancelEditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelEditUserActionPerformed
        editUserId = null;
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelEditUserActionPerformed

    private void userShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userShowPasswordActionPerformed
        if(userShowPassword.isSelected()){
            userPassword.setEchoChar((char)0);
            userShowPassword.setText("Hide Password");
        }
        else{
            userPassword.setEchoChar('•');
            userShowPassword.setText("Show Password");
        }
    }//GEN-LAST:event_userShowPasswordActionPerformed

    public void getEditData() {
        con = DBConnect.connect();
        
        try {
            cs = (com.mysql.jdbc.CallableStatement) con.prepareCall("{call `SearchUsersDetails`('"+editId+"')}");
            rs = cs.executeQuery();
            
            if(rs.next()){
                userType.setText(rs.getString("Role"));
                userFName.setText(rs.getString("First Name"));
                userLName.setText(rs.getString("Last Name"));
                userDob.setDate(rs.getDate("DOB"));
                if("M".equals(rs.getString("Gender"))){
                    userGender.setSelectedIndex(0);
                } else {
                    userGender.setSelectedIndex(1);
                }
                userNicNo.setText(rs.getString("NIC"));
                userAddress.setText(rs.getString("Address"));
                userContactNo.setText(rs.getString("Contact"));
                userEmail.setText(rs.getString("Email"));
                if(null==rs.getString("Department")){
                    userDepartment.setSelectedIndex(2);
                } else switch (rs.getString("Department")) {
                    case "ICT":
                        userDepartment.setSelectedIndex(0);
                        break;
                    case "ENT":
                        userDepartment.setSelectedIndex(1);
                        break;
                    default:
                        userDepartment.setSelectedIndex(2);
                        break;
                }
                userId.setText(rs.getString("Id"));
                userPassword.setText(rs.getString("Password"));
                
           }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EditProfile().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addUser;
    private javax.swing.JLabel addUserMessage;
    private javax.swing.JButton btnCancelEditUser;
    private javax.swing.JButton btnUpdateImage;
    private javax.swing.JButton btnUpdateUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea userAddress;
    private javax.swing.JTextField userContactNo;
    private javax.swing.JComboBox<String> userDepartment;
    private com.toedter.calendar.JDateChooser userDob;
    private javax.swing.JTextField userEmail;
    private javax.swing.JTextField userFName;
    private javax.swing.JComboBox<String> userGender;
    private javax.swing.JTextField userId;
    private javax.swing.JTextField userLName;
    private javax.swing.JTextField userNicNo;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JLabel userProfilePic;
    private javax.swing.JCheckBox userShowPassword;
    private javax.swing.JTextField userType;
    // End of variables declaration//GEN-END:variables
}
