/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package tecmis;

import com.mysql.jdbc.CallableStatement;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sanda
 */
public class Login extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    CallableStatement cs = null;
   
            
    /** Creates new form Login */
    public Login() {
        initComponents();
        
        this.setIconImage(new ImageIcon(getClass().getResource("/image/tecmis.png")).getImage());
    }
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backColor = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel1 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        showPassword = new javax.swing.JCheckBox();
        loginIcon = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        incorrectMsg = new javax.swing.JLabel();
        btn_forgot = new javax.swing.JLabel();
        btn_clear = new javax.swing.JButton();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("L O G I N");
        setUndecorated(true);
        setResizable(false);

        backColor.setBackground(new java.awt.Color(13, 20, 40));
        backColor.setPreferredSize(new java.awt.Dimension(700, 350));

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setText("User Name :");

        passwordLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        passwordLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel1.setText("Password :");

        userName.setBackground(new java.awt.Color(13, 20, 40));
        userName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        userName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userName.setName(""); // NOI18N
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameMouseClicked(evt);
            }
        });
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(0, 137, 95));
        btn_login.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("LOGIN");
        btn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_loginMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_loginMouseReleased(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        password.setBackground(new java.awt.Color(13, 20, 40));
        password.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordMouseClicked(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordKeyPressed(evt);
            }
        });

        showPassword.setBackground(new java.awt.Color(13, 20, 40));
        showPassword.setForeground(new java.awt.Color(153, 153, 153));
        showPassword.setText("Show Password");
        showPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show.png"))); // NOI18N
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        loginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/userIcon.png"))); // NOI18N

        loginLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setText("Sign In");

        incorrectMsg.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        incorrectMsg.setForeground(new java.awt.Color(255, 0, 0));

        btn_forgot.setForeground(new java.awt.Color(153, 153, 153));
        btn_forgot.setText("Forgot Your Password ?");
        btn_forgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_forgotMouseClicked(evt);
            }
        });

        btn_clear.setBackground(new java.awt.Color(0, 137, 95));
        btn_clear.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("CLEAR");
        btn_clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_clearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_clearMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_clearMouseReleased(evt);
            }
        });
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close.png"))); // NOI18N
        close.setToolTipText("Close");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/minimize.png"))); // NOI18N
        minimize.setToolTipText("Minimize");
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/tecmis.png"))); // NOI18N
        title.setText("T E C M I S");

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout backColorLayout = new javax.swing.GroupLayout(backColor);
        backColor.setLayout(backColorLayout);
        backColorLayout.setHorizontalGroup(
            backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backColorLayout.createSequentialGroup()
                .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backColorLayout.createSequentialGroup()
                        .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backColorLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backColorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(loginLabel)
                                .addGap(112, 112, 112)))
                        .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(incorrectMsg)
                            .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(backColorLayout.createSequentialGroup()
                                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(20, 20, 20)
                                    .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backColorLayout.createSequentialGroup()
                                    .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordLabel1)
                                        .addComponent(userNameLabel)
                                        .addComponent(showPassword)
                                        .addComponent(btn_forgot))
                                    .addGap(24, 24, 24))))
                        .addGap(0, 90, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backColorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(backColorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backColorLayout.setVerticalGroup(
            backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backColorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backColorLayout.createSequentialGroup()
                        .addComponent(userNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginLabel))
                .addGap(18, 18, 18)
                .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backColorLayout.createSequentialGroup()
                        .addComponent(passwordLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showPassword)
                        .addGap(18, 18, 18)
                        .addComponent(btn_forgot)
                        .addGap(20, 20, 20)
                        .addGroup(backColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(incorrectMsg)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backColor, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if(showPassword.isSelected()){
            password.setEchoChar((char)0);
            showPassword.setText("Hide Password");
            showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide.png")));
        }
        else{
            password.setEchoChar('•');
            showPassword.setText("Show Password");
            showPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/show.png")));
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
                
        logUser();
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseEntered
        btn_login.setBackground(new Color(0, 86, 83));
    }//GEN-LAST:event_btn_loginMouseEntered

    private void btn_loginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseReleased
        btn_login.setBackground(new Color(0, 137, 95));
    }//GEN-LAST:event_btn_loginMouseReleased

    private void btn_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseExited
        btn_login.setBackground(new Color(0, 137, 95));
    }//GEN-LAST:event_btn_loginMouseExited

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void btn_forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_forgotMouseClicked
        
        forgotPassword();
    }//GEN-LAST:event_btn_forgotMouseClicked

    private void btn_clearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseEntered
        btn_clear.setBackground(new Color(0, 86, 83));
    }//GEN-LAST:event_btn_clearMouseEntered

    private void btn_clearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseExited
        btn_clear.setBackground(new Color(0, 137, 95));
    }//GEN-LAST:event_btn_clearMouseExited

    private void btn_clearMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clearMouseReleased
        btn_clear.setBackground(new Color(0, 137, 95));
    }//GEN-LAST:event_btn_clearMouseReleased

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        userName.setText(null);
        password.setText(null);
        userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        incorrectMsg.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void userNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseClicked
        userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        incorrectMsg.setText("");
    }//GEN-LAST:event_userNameMouseClicked

    private void passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordMouseClicked
        userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        incorrectMsg.setText("");
    }//GEN-LAST:event_passwordMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back_h.png")));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png")));
    }//GEN-LAST:event_backMouseExited

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Welcome w = new Welcome();
        
        w.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backMouseClicked

    private void passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            logUser();
        }
    }//GEN-LAST:event_passwordKeyPressed

    public void logUser()
    {
        String user = userName.getText().trim();
        String pwd = password.getText().trim();
        
        if(user.isEmpty() && pwd.isEmpty()){
            incorrectMsg.setText("Please Enter Your Username & Password !");
            userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
            password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        }
        else if(user.isEmpty()){
            incorrectMsg.setText("Please Enter Your Username !");
            userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
            password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        }
        else if(pwd.isEmpty()){
            incorrectMsg.setText("Please Enter Your Password !");
            userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
            password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
        }
        else{
            
            incorrectMsg.setText("");
            userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
            password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
                        
            try {
                con = DBConnect.connect();
                cs = (CallableStatement) con.prepareCall("{call login(?)}");
                cs.setString("username", user);
                rs = cs.executeQuery();                
                con = null;
                
                if(rs.next())
                {
                    
                    if(pwd.equals(rs.getString("password")) && rs.getString("role").equals("admin"))
                    {
                        new AdminDashboard().setUser(user);
                        new AdminDashboard().setVisible(true);
                        this.setVisible(false);
                    }
                    else if(pwd.equals(rs.getString("password")) && rs.getString("role").equals("student"))
                    {
                        new StudentDashboard().setUser(user);
                        new StudentDashboard().setVisible(true);
                        this.setVisible(false);
                    }
                    else if(pwd.equals(rs.getString("password")) && rs.getString("role").equals("lecturer"))
                    {
                        new LecturerDashboard().setUser(user);
                        new LecturerDashboard().setVisible(true);
                        this.setVisible(false);
                    }
                    else if(pwd.equals(rs.getString("password")) && rs.getString("role").equals("technical officer"))
                    {
                        new TechOfficerDashboard().setUser(user);
                        new TechOfficerDashboard().setVisible(true);
                        this.setVisible(false);
                    }
                    else
                    {
                        incorrectMsg.setText("Password incorrect");
                        password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                        password.setText(null);
                    }
                    
                }
                else{
                    incorrectMsg.setText("User does not exist");
                    userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    userName.setText(null);
                    password.setText(null);
                }
            } catch (SQLException e) {
                new DBError().setVisible(true);
                this.setEnabled(false);
            }
            
        }
    }
    
    public void forgotPassword()
    {
        String user = userName.getText().trim();
        
        if(userName.getText().trim().isEmpty()){
            incorrectMsg.setText("Username is Required !");
            userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
            password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
        }
        else{
            
            try {
                             
                con=DBConnect.connect();
                cs = (CallableStatement) con.prepareCall("{CALL `GetEmail`(?)}");
                cs.setString("searchId", user);
                rs = cs.executeQuery();
                con = null;
                
                if(rs.next())
                {
                    userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
                    password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 137, 95), 2, true));
                    incorrectMsg.setText(null);
                    try {
                        RecoverPwd.sendMail(rs.getString("email"),rs.getString("password"));
                        JOptionPane.showMessageDialog(null,"The password was sent to your email..");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null,e.getMessage());
                    }
                }
                else{
                    incorrectMsg.setText("User does not exist");
                    userName.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));
                    userName.setText(null);
                    password.setText(null);
                }
            }
            catch(HeadlessException | SQLException e){
                new DBError().setVisible(true);
                incorrectMsg.setText("Server error");
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel backColor;
    private javax.swing.JButton btn_clear;
    private javax.swing.JLabel btn_forgot;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel close;
    private javax.swing.JLabel incorrectMsg;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel minimize;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel1;
    private javax.swing.JCheckBox showPassword;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables

}
